import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Footer } from "@/components/home-page/footer";
import { ConditionalLayout } from "@/components/layout/conditional-layout";
import QueryProvider from "@/components/query-provider";
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ConditionalLayout>
            <Toaster
              position="top-right"
              theme="dark"
              richColors
              duration={3000}
            />
            {children}
          </ConditionalLayout>
        </QueryProvider>
      </body>
    </html>
  );
}
